# Generated by Django 4.2.26 on 2025-12-03 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='context',
            new_name='content',
        ),
    ]
